version: '3.9'

services:
  static:
    build: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - images:/usr/share/nginx/html/images
    networks:
      - nginx_network

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    networks:
      - db-data

  web:
    build:
      context: api
    stop_signal: SIGKILL
    ports:
      - 8000:8000
    expose:
      - 8000
    restart: always
    env_file:
      - api/gunicorn.env
    depends_on:
      - db
    volumes:
      - images:/api/images
      - /api/app/:/app/
    networks:
      - nginx_network
      - db-data

volumes:
  images:
    driver: local

networks:
  nginx_network:
    driver: bridge
  db-data:
    driver: bridge