[tool.black]
line-length = 79

#[tool.isort]
#profile = "black"
#multi_line_output = 3
#include_trailing_comma = true
#
#[tool.flake8]
#multi_line_output = 3
#include_trailing_comma = true
#inline-quotes = "